import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard, Users, CalendarCheck2, WalletCards, ReceiptText, Settings, Plus, Search, Check, X, Clock3, IndianRupee, UserPlus, ArrowUpRight, ChevronDown, MoreHorizontal, Phone, BadgeIndianRupee, Building2, MapPin, FileText, ShieldCheck, Database, Download, Printer, Trash2, Pencil, Package, HandCoins, UtensilsCrossed, Bus, AlertCircle, Menu, ChevronLeft, Save, Cloud, RefreshCw} from 'lucide-react';
import './styles.css';

const BUSINESS={name:'Bhansali Medisales',address:'Gurukrupa Niwas, 1st Floor, Above Janaseva Bank, Pune-Saswad Road, Bhekrainagar, Phursungi, Pune - 412308, Maharashtra',gstin:'27AETPN3884L3ZG',drug:'DL-MH-PZ3-637086/637087',fssai:'30260602124690462'};
const pad=n=>String(n).padStart(2,'0');
const isoDate=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const today=isoDate(new Date());
const monthKey=today.slice(0,7);
const seedEmployees=[
 {id:'BMS-001',name:'Amit Sharma',phone:'98765 43210',pan:'BCQPS4582M',designation:'Sales Executive',salary:24000,status:'Active',joined:'2025-06-12'},
 {id:'BMS-002',name:'Priya Patil',phone:'98220 14589',pan:'DNWPP7654K',designation:'Billing Assistant',salary:22000,status:'Active',joined:'2025-08-04'},
 {id:'BMS-003',name:'Rahul Jadhav',phone:'97654 82017',pan:'AFGPJ3381D',designation:'Delivery Associate',salary:18000,status:'Active',joined:'2026-01-18'},
 {id:'BMS-004',name:'Neha Kulkarni',phone:'98901 67234',pan:'EMKPK9012R',designation:'Store Assistant',salary:20000,status:'Active',joined:'2025-11-01'},
];
const seedExpenses=[
 {id:'EXP-104',employeeId:'BMS-003',date:`${monthKey}-18`,category:'Advance',amount:2500,description:'Salary advance'},
 {id:'EXP-103',employeeId:'BMS-001',date:`${monthKey}-15`,category:'Product',amount:850,description:'Medicines taken from shop'},
 {id:'EXP-102',employeeId:'BMS-004',date:`${monthKey}-11`,category:'Travel',amount:320,description:'Local delivery travel'},
 {id:'EXP-101',employeeId:'BMS-002',date:`${monthKey}-07`,category:'Other',amount:450,description:'Lunch expense'},
];
const sampleAttendance=()=>{const a=[];const now=new Date();for(let day=1;day<=Math.min(now.getDate(),24);day++){seedEmployees.forEach((e,i)=>{if(day%7!==0)a.push({employeeId:e.id,date:`${monthKey}-${pad(day)}`,status:(day+i*3)%11===0?'Absent':'Present'});});}return a;};
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0);
const fmtDate=s=>new Date(`${s}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
const initials=n=>n.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();
const colors=['violet','blue','amber','rose','teal'];
const daysInMonth=m=>{const [y,mo]=m.split('-').map(Number);return new Date(y,mo,0).getDate()};

function consumePrivateSetup(){
 if(!location.hash.startsWith('#setup='))return;
 try{
  const raw=location.hash.slice(7).replace(/-/g,'+').replace(/_/g,'/');
  const config=JSON.parse(decodeURIComponent(escape(atob(raw))));
  if(config.url&&config.token){localStorage.setItem('bms-sheet-url',config.url);localStorage.setItem('bms-sheet-token',config.token)}
 }catch{}
 history.replaceState(null,'',location.pathname+location.search);
}
consumePrivateSetup();

function useStore(){
 const [data,setData]=useState(()=>{const saved=localStorage.getItem('bms-payroll-v2');return saved?JSON.parse(saved):{employees:seedEmployees,attendance:sampleAttendance(),expenses:seedExpenses,payroll:[]}});
 useEffect(()=>localStorage.setItem('bms-payroll-v2',JSON.stringify(data)),[data]);
 return [data,setData];
}

function App(){
 const [page,setPage]=useState('Dashboard'),[mobile,setMobile]=useState(false),[data,setData]=useStore(),[modal,setModal]=useState(null),[sheetUrl,setSheetUrl]=useState(localStorage.getItem('bms-sheet-url')||''),[sheetToken,setSheetToken]=useState(localStorage.getItem('bms-sheet-token')||''),[sync,setSync]=useState('demo'),[cloudReady,setCloudReady]=useState(false);
 const syncTimer=useRef(null);
 const [selectedDate,setSelectedDate]=useState(today),[selectedMonth,setSelectedMonth]=useState(monthKey),[query,setQuery]=useState('');
 const active=data.employees.filter(e=>e.status==='Active');
 const monthAtt=data.attendance.filter(a=>a.date.startsWith(selectedMonth));
 const monthExp=data.expenses.filter(e=>e.date.startsWith(selectedMonth));
 const attendanceFor=id=>monthAtt.filter(a=>a.employeeId===id&&a.status==='Present').length;
 const employeeExpense=id=>monthExp.filter(e=>e.employeeId===id).reduce((s,e)=>s+Number(e.amount),0);
 const payrollFor=e=>{const days=daysInMonth(selectedMonth),worked=attendanceFor(e.id),gross=e.salary/days*worked,deduct=employeeExpense(e.id);return{days,worked,daily:e.salary/days,gross,deduct,net:Math.max(0,gross-deduct)}};
 const saveEmployee=(form)=>{setData(d=>({...d,employees:[...d.employees,{...form,id:`BMS-${String(Math.max(0,...d.employees.map(e=>Number(e.id.split('-')[1])||0))+1).padStart(3,'0')}`,salary:Number(form.salary),status:'Active'}]}));setModal(null)};
 const saveExpense=(form)=>{setData(d=>({...d,expenses:[{...form,id:`EXP-${Date.now().toString().slice(-6)}`,amount:Number(form.amount)},...d.expenses]}));setModal(null)};
 const setAttendance=(employeeId,status)=>setData(d=>({...d,attendance:[...d.attendance.filter(a=>!(a.employeeId===employeeId&&a.date===selectedDate)),{employeeId,date:selectedDate,status}]}));
 const request=async(url,body)=>{const res=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});const json=await res.json();if(!json.ok)throw new Error(json.error||'Google Sheets request failed');return json};
 const loadCloud=async(url,token)=>{if(!url||!token)return;setSync('syncing');try{const json=await request(url,{action:'load',token});setData(json.data);setCloudReady(true);setSync('connected')}catch{setSync('error')}};
 useEffect(()=>{if(sheetUrl&&sheetToken)loadCloud(sheetUrl,sheetToken)},[]);
 useEffect(()=>{if(!sheetUrl||!cloudReady)return;clearTimeout(syncTimer.current);syncTimer.current=setTimeout(()=>doSync(),800);return()=>clearTimeout(syncTimer.current)},[data,sheetUrl,cloudReady]);
 const connectSheet=async({url,token})=>{if(!url){localStorage.removeItem('bms-sheet-url');localStorage.removeItem('bms-sheet-token');setSheetUrl('');setSheetToken('');setCloudReady(false);setSync('demo');setModal(null);return}localStorage.setItem('bms-sheet-url',url);localStorage.setItem('bms-sheet-token',token);setSheetUrl(url);setSheetToken(token);setModal(null);await loadCloud(url,token)};
 const doSync=async()=>{if(!sheetUrl||!sheetToken){setModal('settings');return}setSync('syncing');try{await request(sheetUrl,{action:'syncAll',token:sheetToken,data});setSync('connected')}catch{setSync('error')}};
 const nav=['Dashboard','Employees','Attendance','Expenses','Payslips'];
 return <div className="app">
  <aside className={mobile?'sidebar open':'sidebar'}>
   <div className="brand"><div className="brandmark">BM</div><div><b>Bhansali</b><span>Medisales</span></div></div>
   <nav>{nav.map(n=>{const I={Dashboard:LayoutDashboard,Employees:Users,Attendance:CalendarCheck2,Expenses:WalletCards,Payslips:ReceiptText}[n];return <button key={n} className={page===n?'active':''} onClick={()=>{setPage(n);setMobile(false)}}><I size={19}/><span>{n}</span>{n==='Attendance'&&<em>{active.length}</em>}</button>})}</nav>
   <div className="side-bottom"><div className="sync-card"><div className="sync-icon"><Database size={18}/></div><b>Google Sheets</b><span>{sheetUrl?'Backup connected':'Connect your backup'}</span><button onClick={()=>setModal('settings')}>{sheetUrl?'Manage connection':'Set up now'}</button></div><button className="settings" onClick={()=>setModal('settings')}><Settings size={18}/> Settings</button></div>
  </aside>
  {mobile&&<div className="scrim" onClick={()=>setMobile(false)}/>} 
  <main>
   <header><button className="menubtn" onClick={()=>setMobile(true)}><Menu/></button><div><h1>{page}</h1><p>{page==='Dashboard'?'Your team and payroll at a glance':page==='Attendance'?'Mark and review daily attendance':page==='Expenses'?'Track advances, products and other deductions':page==='Payslips'?'Review salary calculations and print payslips':'Manage employee records'}</p></div><div className="header-actions"><div className={`sync ${sync}`}><span></span>{sync==='syncing'?'Syncing…':sync==='error'?'Sync failed':sheetUrl?'Google Sheet connected':'Demo mode'}</div>{sheetUrl&&<button className="iconbtn" onClick={doSync}><RefreshCw size={18}/></button>}<button className="primary" onClick={()=>setModal(page==='Expenses'?'expense':'employee')}><Plus size={18}/>{page==='Expenses'?'Add expense':'Add employee'}</button></div></header>
   <div className="content">
    {page==='Dashboard'&&<Dashboard data={data} active={active} payrollFor={payrollFor} expenses={monthExp} setPage={setPage} setModal={setModal} selectedMonth={selectedMonth}/>} 
    {page==='Employees'&&<Employees employees={data.employees} query={query} setQuery={setQuery} setModal={setModal}/>} 
    {page==='Attendance'&&<Attendance employees={active} attendance={data.attendance} date={selectedDate} setDate={setSelectedDate} setAttendance={setAttendance}/>} 
    {page==='Expenses'&&<Expenses expenses={data.expenses} employees={data.employees} query={query} setQuery={setQuery} setModal={setModal} remove={id=>setData(d=>({...d,expenses:d.expenses.filter(e=>e.id!==id)}))}/>} 
    {page==='Payslips'&&<Payslips employees={active} month={selectedMonth} setMonth={setSelectedMonth} payrollFor={payrollFor} setModal={setModal}/>} 
   </div>
  </main>
  {modal==='employee'&&<EmployeeModal close={()=>setModal(null)} save={saveEmployee}/>} 
  {modal==='expense'&&<ExpenseModal close={()=>setModal(null)} save={saveExpense} employees={active}/>} 
  {modal==='settings'&&<SettingsModal close={()=>setModal(null)} save={connectSheet} value={sheetUrl} tokenValue={sheetToken}/>} 
  {modal?.type==='payslip'&&<PayslipModal close={()=>setModal(null)} employee={modal.employee} month={selectedMonth} pay={payrollFor(modal.employee)} expenses={monthExp.filter(e=>e.employeeId===modal.employee.id)}/>} 
 </div>
}

function Dashboard({data,active,payrollFor,expenses,setPage,setModal,selectedMonth}){const present=data.attendance.filter(a=>a.date===today&&a.status==='Present').length;const marked=data.attendance.filter(a=>a.date===today).length;const payroll=active.reduce((s,e)=>s+payrollFor(e).net,0);const deduction=expenses.reduce((s,e)=>s+Number(e.amount),0);return <>
 <section className="hero"><div><span className="eyebrow">{new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</span><h2>Good afternoon! <span>Here’s today’s overview.</span></h2></div><button className="whitebtn" onClick={()=>setPage('Attendance')}><CalendarCheck2 size={18}/>Mark attendance<ArrowUpRight size={17}/></button></section>
 <div className="stats">
  <Stat icon={Users} tone="violet" label="Total employees" value={active.length} note={`${active.length} active employees`}/>
  <Stat icon={CalendarCheck2} tone="green" label="Present today" value={`${present}/${active.length}`} note={marked<active.length?`${active.length-marked} attendance pending`:`${active.length-present} absent today`}/>
  <Stat icon={BadgeIndianRupee} tone="blue" label="Estimated payroll" value={money(payroll)} note={new Date(selectedMonth+'-01').toLocaleDateString('en-IN',{month:'long',year:'numeric'})}/>
  <Stat icon={WalletCards} tone="orange" label="Monthly deductions" value={money(deduction)} note={`${expenses.length} expense entries`}/>
 </div>
 <div className="grid-main">
  <section className="panel"><PanelHead title="Today’s attendance" sub={`${marked} of ${active.length} employees marked`} action="View all" onClick={()=>setPage('Attendance')}/><div className="attendance-list">{active.slice(0,5).map((e,i)=>{const a=data.attendance.find(a=>a.employeeId===e.id&&a.date===today);return <div className="employee-row" key={e.id}><Avatar name={e.name} i={i}/><div className="grow"><b>{e.name}</b><span>{e.designation}</span></div><Status status={a?.status||'Not marked'}/></div>})}</div></section>
  <section className="panel"><PanelHead title="Recent expenses" sub="Latest employee deductions" action="View all" onClick={()=>setPage('Expenses')}/><div className="expense-list">{data.expenses.slice(0,4).map((x,i)=>{const e=data.employees.find(e=>e.id===x.employeeId);return <div className="expense-row" key={x.id}><div className={`expense-icon ${x.category.toLowerCase()}`}>{x.category==='Advance'?<HandCoins/>:x.category==='Product'?<Package/>:x.category==='Travel'?<Bus/>:<UtensilsCrossed/>}</div><div className="grow"><b>{x.description}</b><span>{e?.name} · {fmtDate(x.date)}</span></div><strong>-{money(x.amount)}</strong></div>})}</div></section>
 </div>
 <section className="panel payroll-preview"><PanelHead title="This month’s payroll" sub="Calculated from attendance and deductions" action="View payslips" onClick={()=>setPage('Payslips')}/><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Days worked</th><th>Monthly salary</th><th>Deductions</th><th>Net payable</th><th></th></tr></thead><tbody>{active.map((e,i)=>{const p=payrollFor(e);return <tr key={e.id}><td><div className="person"><Avatar name={e.name} i={i}/><div><b>{e.name}</b><span>{e.id}</span></div></div></td><td><b>{p.worked}</b> <span className="muted">/ {p.days}</span></td><td>{money(e.salary)}</td><td className="negative">-{money(p.deduct)}</td><td><strong>{money(p.net)}</strong></td><td><button className="plain" onClick={()=>setModal({type:'payslip',employee:e})}>View slip</button></td></tr>})}</tbody></table></div></section>
 </>}
function Stat({icon:Icon,tone,label,value,note}){return <div className="stat"><div className={`stat-icon ${tone}`}><Icon/></div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>}
function PanelHead({title,sub,action,onClick}){return <div className="panel-head"><div><h3>{title}</h3><p>{sub}</p></div><button onClick={onClick}>{action}<ArrowUpRight size={15}/></button></div>}
function Avatar({name,i=0}){return <div className={`avatar ${colors[i%colors.length]}`}>{initials(name)}</div>}
function Status({status}){return <span className={`status ${status.toLowerCase().replace(' ','-')}`}>{status==='Present'?<Check/>:status==='Absent'?<X/>:<Clock3/>}{status}</span>}

function Employees({employees,query,setQuery,setModal}){const list=employees.filter(e=>(e.name+e.phone+e.id+e.designation).toLowerCase().includes(query.toLowerCase()));return <section className="panel full"><Toolbar query={query} setQuery={setQuery} placeholder="Search name, phone or employee ID"/><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Phone</th><th>PAN card</th><th>Designation</th><th>Monthly salary</th><th>Status</th><th></th></tr></thead><tbody>{list.map((e,i)=><tr key={e.id}><td><div className="person"><Avatar name={e.name} i={i}/><div><b>{e.name}</b><span>{e.id} · Joined {fmtDate(e.joined)}</span></div></div></td><td>{e.phone}</td><td className="mono">{e.pan}</td><td>{e.designation}</td><td><strong>{money(e.salary)}</strong></td><td><span className="dot-active">{e.status}</span></td><td><button className="iconbtn"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table></div></section>}
function Toolbar({query,setQuery,placeholder}){return <div className="toolbar"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder}/></div><button className="filter">All employees<ChevronDown size={16}/></button></div>}

function Attendance({employees,attendance,date,setDate,setAttendance}){const marked=attendance.filter(a=>a.date===date);const p=marked.filter(a=>a.status==='Present').length,a=marked.filter(a=>a.status==='Absent').length;return <><div className="attendance-top"><div className="date-control"><CalendarCheck2/><div><span>Attendance date</span><input type="date" value={date} max={today} onChange={e=>setDate(e.target.value)}/></div></div><div className="attendance-summary"><div><b>{p}</b><span>Present</span></div><div><b>{a}</b><span>Absent</span></div><div><b>{employees.length-p-a}</b><span>Not marked</span></div></div></div><section className="panel full"><div className="panel-head"><div><h3>Employee attendance</h3><p>Select present or absent for each employee</p></div><span className="progress-text">{marked.length} of {employees.length} completed</span></div><div className="mark-list">{employees.map((e,i)=>{const s=marked.find(x=>x.employeeId===e.id)?.status;return <div className="mark-row" key={e.id}><Avatar name={e.name} i={i}/><div className="grow"><b>{e.name}</b><span>{e.designation} · {e.id}</span></div><div className="mark-actions"><button className={s==='Present'?'present selected':'present'} onClick={()=>setAttendance(e.id,'Present')}><Check/>Present</button><button className={s==='Absent'?'absent selected':'absent'} onClick={()=>setAttendance(e.id,'Absent')}><X/>Absent</button></div></div>})}</div></section></>}

function Expenses({expenses,employees,query,setQuery,setModal,remove}){const list=expenses.filter(x=>{const e=employees.find(e=>e.id===x.employeeId);return (x.description+x.category+e?.name).toLowerCase().includes(query.toLowerCase())});return <><div className="expense-summary"><div><span>Total expenses this month</span><strong>{money(expenses.filter(e=>e.date.startsWith(monthKey)).reduce((s,e)=>s+e.amount,0))}</strong><small>Will be deducted from employee salaries</small></div><WalletCards/></div><section className="panel full"><Toolbar query={query} setQuery={setQuery} placeholder="Search expenses or employee"/><div className="table-wrap"><table><thead><tr><th>Date</th><th>Employee</th><th>Type</th><th>Description</th><th>Amount</th><th></th></tr></thead><tbody>{list.map((x,i)=>{const e=employees.find(e=>e.id===x.employeeId);return <tr key={x.id}><td>{fmtDate(x.date)}</td><td><div className="person compact"><Avatar name={e?.name||'?'} i={i}/><div><b>{e?.name}</b><span>{e?.id}</span></div></div></td><td><span className={`category ${x.category.toLowerCase()}`}>{x.category}</span></td><td>{x.description}</td><td className="negative"><strong>-{money(x.amount)}</strong></td><td><button className="iconbtn danger" onClick={()=>remove(x.id)}><Trash2 size={16}/></button></td></tr>})}</tbody></table></div></section></>}

function Payslips({employees,month,setMonth,payrollFor,setModal}){return <><div className="month-bar"><div><span>Salary month</span><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div><p>Salary is calculated using {daysInMonth(month)} calendar days in this month.</p></div><div className="payslip-grid">{employees.map((e,i)=>{const p=payrollFor(e);return <div className="pay-card" key={e.id}><div className="pay-person"><Avatar name={e.name} i={i}/><div><b>{e.name}</b><span>{e.designation} · {e.id}</span></div><button><MoreHorizontal/></button></div><div className="pay-math"><div><span>Days worked</span><b>{p.worked} / {p.days}</b></div><div><span>Earned salary</span><b>{money(p.gross)}</b></div><div><span>Deductions</span><b className="negative">-{money(p.deduct)}</b></div></div><div className="net"><span>Net payable</span><strong>{money(p.net)}</strong></div><button className="slipbtn" onClick={()=>setModal({type:'payslip',employee:e})}><FileText/>View & print payslip</button></div>})}</div></>}

function Modal({children,close,wide=false}){return <div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className={wide?'modal wide':'modal'}>{children}</div></div>}
function EmployeeModal({close,save}){const [f,setF]=useState({name:'',phone:'',pan:'',designation:'',salary:'',joined:today});const field=(k,v)=>setF(x=>({...x,[k]:v}));return <Modal close={close}><ModalHead icon={UserPlus} title="Add new employee" sub="Employee number will be assigned automatically" close={close}/><form onSubmit={e=>{e.preventDefault();save(f)}}><div className="form-grid"><Label text="Full name"><input required value={f.name} onChange={e=>field('name',e.target.value)} placeholder="Employee full name"/></Label><Label text="Phone number"><input required value={f.phone} onChange={e=>field('phone',e.target.value)} placeholder="10-digit number"/></Label><Label text="PAN card number"><input required value={f.pan} onChange={e=>field('pan',e.target.value.toUpperCase())} placeholder="ABCDE1234F" pattern="[A-Z]{5}[0-9]{4}[A-Z]"/></Label><Label text="Designation"><input required value={f.designation} onChange={e=>field('designation',e.target.value)} placeholder="e.g. Sales Executive"/></Label><Label text="Monthly salary"><div className="input-icon">₹<input required type="number" min="0" value={f.salary} onChange={e=>field('salary',e.target.value)} placeholder="0"/></div></Label><Label text="Joining date"><input required type="date" value={f.joined} onChange={e=>field('joined',e.target.value)}/></Label></div><FormActions close={close} text="Add employee"/></form></Modal>}
function ExpenseModal({close,save,employees}){const [f,setF]=useState({employeeId:employees[0]?.id||'',date:today,category:'Advance',amount:'',description:''});const field=(k,v)=>setF(x=>({...x,[k]:v}));return <Modal close={close}><ModalHead icon={WalletCards} title="Add employee expense" sub="This amount will be deducted from salary" close={close}/><form onSubmit={e=>{e.preventDefault();save(f)}}><Label text="Employee"><select value={f.employeeId} onChange={e=>field('employeeId',e.target.value)}>{employees.map(e=><option key={e.id} value={e.id}>{e.name} — {e.id}</option>)}</select></Label><div className="form-grid"><Label text="Date"><input type="date" value={f.date} onChange={e=>field('date',e.target.value)}/></Label><Label text="Expense type"><select value={f.category} onChange={e=>field('category',e.target.value)}><option>Advance</option><option>Product</option><option>Travel</option><option>Other</option></select></Label></div><Label text="Amount"><div className="input-icon">₹<input required type="number" min="1" value={f.amount} onChange={e=>field('amount',e.target.value)} placeholder="0"/></div></Label><Label text="Description"><textarea required value={f.description} onChange={e=>field('description',e.target.value)} placeholder="What was this expense for?"/></Label><FormActions close={close} text="Add expense"/></form></Modal>}
function SettingsModal({close,save,value,tokenValue}){const [url,setUrl]=useState(value),[token,setToken]=useState(tokenValue);return <Modal close={close}><ModalHead icon={Database} title="Google Sheets connection" sub="Connect the deployed Apps Script web app" close={close}/><div className="info-box"><ShieldCheck/><div><b>Your data stays in your Google Sheet</b><span>Every request requires the private token created by your Apps Script.</span></div></div><Label text="Apps Script web app URL"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://script.google.com/macros/s/.../exec"/></Label><Label text="Private access token"><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Paste the token from the Apps Script execution log"/></Label><div className="setup-steps"><b>Quick setup</b><ol><li>Open the provided Google Sheet.</li><li>Open Extensions → Apps Script and paste <code>google-apps-script/Code.gs</code>.</li><li>Run <code>setupWorkbook</code>; copy the token from the execution log.</li><li>Deploy as a web app, then paste the URL and token above.</li></ol></div><div className="form-actions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>save({url,token})} disabled={!url||!token}><Cloud/>Save connection</button></div></Modal>}
function ModalHead({icon:Icon,title,sub,close}){return <div className="modal-head"><div className="modal-icon"><Icon/></div><div><h2>{title}</h2><p>{sub}</p></div><button onClick={close}><X/></button></div>}
function Label({text,children}){return <label><span>{text}</span>{children}</label>}
function FormActions({close,text}){return <div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" type="submit"><Save/>{text}</button></div>}

function PayslipModal({close,employee,month,pay,expenses}){const monthName=new Date(month+'-01').toLocaleDateString('en-IN',{month:'long',year:'numeric'});return <Modal close={close} wide><div className="payslip-actions no-print"><button className="secondary" onClick={close}><ChevronLeft/>Back</button><button className="primary" onClick={()=>window.print()}><Printer/>Print payslip</button></div><article className="payslip"><div className="slip-brand"><div className="brandmark">BM</div><div><h2>{BUSINESS.name}</h2><p>Employee salary statement</p></div></div><div className="slip-business"><div><MapPin/><span>{BUSINESS.address}</span></div><div><b>GSTIN</b><span>{BUSINESS.gstin}</span></div><div><b>Drug Licence</b><span>{BUSINESS.drug}</span></div><div><b>FSSAI</b><span>{BUSINESS.fssai}</span></div></div><div className="slip-title"><span>Payslip for</span><h1>{monthName}</h1></div><div className="slip-employee"><div><span>Employee name</span><b>{employee.name}</b></div><div><span>Employee number</span><b>{employee.id}</b></div><div><span>Designation</span><b>{employee.designation}</b></div><div><span>PAN number</span><b>{employee.pan}</b></div></div><table className="slip-table"><thead><tr><th>Earnings</th><th>Calculation</th><th>Amount</th></tr></thead><tbody><tr><td>Monthly salary</td><td>{money(employee.salary)} ÷ {pay.days} days</td><td>{money(employee.salary)}</td></tr><tr><td>Salary earned</td><td>{pay.worked} days × {money(pay.daily)}</td><td>{money(pay.gross)}</td></tr></tbody></table><table className="slip-table deductions"><thead><tr><th>Deductions</th><th>Description</th><th>Amount</th></tr></thead><tbody>{expenses.length?expenses.map(x=><tr key={x.id}><td>{x.category}<small>{fmtDate(x.date)}</small></td><td>{x.description}</td><td>{money(x.amount)}</td></tr>):<tr><td colSpan="2">No deductions this month</td><td>{money(0)}</td></tr>}<tr className="total"><td colSpan="2">Total deductions</td><td>{money(pay.deduct)}</td></tr></tbody></table><div className="slip-net"><div><span>Net salary payable</span><small>Earned salary minus deductions</small></div><strong>{money(pay.net)}</strong></div><div className="slip-foot"><span>This is a computer-generated payslip.</span><b>Authorised Signatory</b></div></article></Modal>}

createRoot(document.getElementById('root')).render(<App/>);
