import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard, Users, CalendarCheck2, WalletCards, ReceiptText, Settings, Plus, Search, Check, X, Clock3, IndianRupee, UserPlus, ArrowUpRight, ChevronDown, MoreHorizontal, Phone, BadgeIndianRupee, Building2, MapPin, FileText, ShieldCheck, Database, Download, Printer, Trash2, Pencil, Package, HandCoins, UtensilsCrossed, Bus, AlertCircle, Menu, ChevronLeft, Save, Cloud, RefreshCw, Store, Fuel} from 'lucide-react';
import './styles.css';

const BUSINESS={name:'Bhansali Medisales',address:'Gurukrupa Niwas, 1st Floor, Above Janaseva Bank, Pune-Saswad Road, Bhekrainagar, Phursungi, Pune - 412308, Maharashtra',gstin:'27AETPN3884L3ZG',drug:'DL-MH-PZ3-637086/637087',fssai:'30260602124690462'};
const LOGO=`${import.meta.env.BASE_URL}bhansali-logo.png`;
const DEFAULT_SHEET_URL='https://script.google.com/macros/s/AKfycbyr7Zqj9gMERgsvrGjKYvqaPGRh_4GVbvjdUgHt1z3FOnR205xw3QspgzHjkOMxBSM/exec';
const pad=n=>String(n).padStart(2,'0');
const isoDate=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const today=isoDate(new Date());
const monthKey=today.slice(0,7);
const seedEmployees=[
 {id:'BMS-001',name:'Amit Sharma',phone:'98765 43210',email:'',pan:'BCQPS4582M',designation:'Sales Executive',salary:24000,status:'Active',joined:'2025-06-12'},
 {id:'BMS-002',name:'Priya Patil',phone:'98220 14589',email:'',pan:'DNWPP7654K',designation:'Billing Assistant',salary:22000,status:'Active',joined:'2025-08-04'},
 {id:'BMS-003',name:'Rahul Jadhav',phone:'97654 82017',email:'',pan:'AFGPJ3381D',designation:'Delivery Associate',salary:18000,status:'Active',joined:'2026-01-18'},
 {id:'BMS-004',name:'Neha Kulkarni',phone:'98901 67234',email:'',pan:'EMKPK9012R',designation:'Store Assistant',salary:20000,status:'Active',joined:'2025-11-01'},
];
const seedExpenses=[
 {id:'EXP-104',employeeId:'BMS-003',date:`${monthKey}-18`,category:'Advance',amount:2500,description:'Salary advance'},
 {id:'EXP-103',employeeId:'BMS-001',date:`${monthKey}-15`,category:'Product',amount:850,description:'Medicines taken from shop'},
 {id:'EXP-102',employeeId:'BMS-004',date:`${monthKey}-11`,category:'Travel',amount:320,description:'Local delivery travel'},
 {id:'EXP-101',employeeId:'BMS-002',date:`${monthKey}-07`,category:'Other',amount:450,description:'Lunch expense'},
];
const sampleAttendance=()=>{const a=[];const now=new Date();for(let day=1;day<=Math.min(now.getDate(),24);day++){seedEmployees.forEach((e,i)=>{if(day%7!==0)a.push({employeeId:e.id,date:`${monthKey}-${pad(day)}`,status:(day+i*3)%11===0?'Absent':'Present'});});}return a;};
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0);
const fmtDate=s=>new Date(`${s}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
const initials=n=>n.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();
const colors=['violet','blue','amber','rose','teal'];
const daysInMonth=m=>{const [y,mo]=m.split('-').map(Number);return new Date(y,mo,0).getDate()};
const normalizeData=raw=>({employees:(raw?.employees||seedEmployees).map(e=>({...e,email:e.email||''})),attendance:raw?.attendance||[],expenses:raw?.expenses||[],employeeStoreExpenses:raw?.employeeStoreExpenses||[],ownerStoreExpenses:raw?.ownerStoreExpenses||[],payroll:raw?.payroll||[]});

function consumePrivateSetup(){
 if(!location.hash.startsWith('#setup='))return;
 try{
  const raw=location.hash.slice(7).replace(/-/g,'+').replace(/_/g,'/');
  const config=JSON.parse(decodeURIComponent(escape(atob(raw))));
  if(config.url&&config.token){localStorage.setItem('bms-sheet-url',config.url);localStorage.setItem('bms-sheet-token',config.token)}
 }catch{}
 history.replaceState(null,'',location.pathname+location.search);
}
consumePrivateSetup();

function useStore(){
 const [data,setData]=useState(()=>{const saved=localStorage.getItem('bms-payroll-v2');return saved?normalizeData(JSON.parse(saved)):normalizeData({employees:seedEmployees,attendance:sampleAttendance(),expenses:seedExpenses})});
 useEffect(()=>localStorage.setItem('bms-payroll-v2',JSON.stringify(data)),[data]);
 return [data,setData];
}

function App(){
 const [page,setPage]=useState('Dashboard'),[mobile,setMobile]=useState(false),[data,setData]=useStore(),[modal,setModal]=useState(null),[sheetUrl,setSheetUrl]=useState(localStorage.getItem('bms-sheet-url')||DEFAULT_SHEET_URL),[sheetToken,setSheetToken]=useState(localStorage.getItem('bms-sheet-token')||''),[sync,setSync]=useState('demo'),[cloudReady,setCloudReady]=useState(false);
 const syncTimer=useRef(null);
 const [selectedDate,setSelectedDate]=useState(today),[selectedMonth,setSelectedMonth]=useState(monthKey),[query,setQuery]=useState('');
 const active=data.employees.filter(e=>e.status==='Active');
 const monthAtt=data.attendance.filter(a=>a.date.startsWith(selectedMonth));
 const monthExp=data.expenses.filter(e=>e.date.startsWith(selectedMonth));
 const attendanceFor=id=>monthAtt.filter(a=>a.employeeId===id&&a.status==='Present').length;
 const employeeExpense=id=>monthExp.filter(e=>e.employeeId===id).reduce((s,e)=>s+Number(e.amount),0);
 const payrollFor=e=>{const days=daysInMonth(selectedMonth),worked=attendanceFor(e.id),gross=e.salary/days*worked,deduct=employeeExpense(e.id);return{days,worked,daily:e.salary/days,gross,deduct,net:Math.max(0,gross-deduct)}};
 const saveEmployee=(form)=>{setData(d=>({...d,employees:[...d.employees,{...form,id:`BMS-${String(Math.max(0,...d.employees.map(e=>Number(e.id.split('-')[1])||0))+1).padStart(3,'0')}`,salary:Number(form.salary),status:'Active'}]}));setModal(null)};
 const saveExpense=(form)=>{setData(d=>({...d,expenses:[{...form,id:`EXP-${Date.now().toString().slice(-6)}`,amount:Number(form.amount)},...d.expenses]}));setModal(null)};
 const saveStoreExpense=(form)=>{const item={date:form.date,category:form.category,amount:Number(form.amount),description:form.description};setData(d=>form.payer==='employee'?{...d,employeeStoreExpenses:[{...item,id:`ESE-${Date.now().toString().slice(-6)}`,employeeId:form.employeeId},...d.employeeStoreExpenses]}:{...d,ownerStoreExpenses:[{...item,id:`OSE-${Date.now().toString().slice(-6)}`},...d.ownerStoreExpenses]});setModal(null)};
 const setAttendance=(employeeId,status)=>setData(d=>({...d,attendance:[...d.attendance.filter(a=>!(a.employeeId===employeeId&&a.date===selectedDate)),{employeeId,date:selectedDate,status}]}));
 const request=async(url,body)=>{const res=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});const json=await res.json();if(!json.ok)throw new Error(json.error||'Google Sheets request failed');return json};
 const loadCloud=async(url,token)=>{if(!url||!token)return;setSync('syncing');try{const json=await request(url,{action:'load',token});setData(current=>{const cloud=normalizeData(json.data);const supportsEmail=(json.data.employees||[]).every(e=>Object.prototype.hasOwnProperty.call(e,'email'));const employees=supportsEmail?cloud.employees:cloud.employees.map(e=>({...e,email:current.employees.find(x=>x.id===e.id)?.email||''}));return{...cloud,employees,employeeStoreExpenses:json.data.employeeStoreExpenses??current.employeeStoreExpenses,ownerStoreExpenses:json.data.ownerStoreExpenses??current.ownerStoreExpenses}});setCloudReady(true);setSync('connected')}catch{setSync('error')}};
 useEffect(()=>{if(sheetUrl&&sheetToken)loadCloud(sheetUrl,sheetToken)},[]);
 useEffect(()=>{if(!sheetUrl||!cloudReady)return;clearTimeout(syncTimer.current);syncTimer.current=setTimeout(()=>doSync(),800);return()=>clearTimeout(syncTimer.current)},[data,sheetUrl,cloudReady]);
 const connectSheet=async({token})=>{if(!token)return;localStorage.setItem('bms-sheet-url',DEFAULT_SHEET_URL);localStorage.setItem('bms-sheet-token',token);setSheetUrl(DEFAULT_SHEET_URL);setSheetToken(token);setModal(null);await loadCloud(DEFAULT_SHEET_URL,token)};
 const doSync=async()=>{if(!sheetUrl||!sheetToken){setModal('settings');return}setSync('syncing');try{await request(sheetUrl,{action:'syncAll',token:sheetToken,data});setSync('connected')}catch{setSync('error')}};
 const nav=['Dashboard','Employees','Attendance','Expenses','Store Expenses','Payslips'];
 const navIcons={Dashboard:LayoutDashboard,Employees:Users,Attendance:CalendarCheck2,Expenses:WalletCards,'Store Expenses':Store,Payslips:ReceiptText};
 return <div className="app">
  <aside className={mobile?'sidebar open':'sidebar'}>
   <div className="brand"><img className="brand-logo" src={LOGO} alt="Bhansali Medisales"/></div>
   <nav>{nav.map(n=>{const I=navIcons[n];return <button key={n} className={page===n?'active':''} onClick={()=>{setPage(n);setMobile(false)}}><I size={19}/><span>{n}</span>{n==='Attendance'&&<em>{active.length}</em>}</button>})}</nav>
   <div className="side-bottom"><div className="sync-card"><div className="sync-icon"><Database size={18}/></div><b>Google Sheets</b><span>{sheetUrl?'Backup connected':'Connect your backup'}</span><button onClick={()=>setModal('settings')}>{sheetUrl?'Manage connection':'Set up now'}</button></div><button className="settings" onClick={()=>setModal('settings')}><Settings size={18}/> Settings</button></div>
  </aside>
  {mobile&&<div className="scrim" onClick={()=>setMobile(false)}/>} 
  <main>
   <header><button className="menubtn" onClick={()=>setMobile(true)}><Menu/></button><div><h1>{page}</h1><p>{page==='Dashboard'?'Your team and payroll at a glance':page==='Attendance'?'Mark and review daily attendance':page==='Expenses'?'Track advances, products and salary deductions':page==='Store Expenses'?'Track business expenses outside employee payroll':page==='Payslips'?'Review salary calculations and print payslips':'Manage employee records'}</p></div><div className="header-actions"><div className={`sync ${sync}`}><span></span>{sync==='syncing'?'Syncing…':sync==='error'?'Sync failed':sheetUrl?'Google Sheet connected':'Demo mode'}</div>{sheetUrl&&<button className="iconbtn" onClick={doSync}><RefreshCw size={18}/></button>}<button className="primary" onClick={()=>setModal(page==='Expenses'?'expense':page==='Store Expenses'?{type:'storeExpense',payer:'employee'}:'employee')}><Plus size={18}/>{page==='Expenses'?'Add expense':page==='Store Expenses'?'Add store expense':'Add employee'}</button></div></header>
   <div className="content">
    {page==='Dashboard'&&<Dashboard data={data} active={active} payrollFor={payrollFor} expenses={monthExp} setPage={setPage} setModal={setModal} selectedMonth={selectedMonth}/>} 
    {page==='Employees'&&<Employees employees={data.employees} query={query} setQuery={setQuery} setModal={setModal}/>} 
    {page==='Attendance'&&<Attendance employees={active} attendance={data.attendance} date={selectedDate} setDate={setSelectedDate} setAttendance={setAttendance}/>} 
    {page==='Expenses'&&<Expenses expenses={data.expenses} employees={data.employees} query={query} setQuery={setQuery} setModal={setModal} remove={id=>setData(d=>({...d,expenses:d.expenses.filter(e=>e.id!==id)}))}/>} 
    {page==='Store Expenses'&&<StoreExpenses employeeExpenses={data.employeeStoreExpenses} ownerExpenses={data.ownerStoreExpenses} employees={data.employees} setModal={setModal} removeEmployee={id=>setData(d=>({...d,employeeStoreExpenses:d.employeeStoreExpenses.filter(e=>e.id!==id)}))} removeOwner={id=>setData(d=>({...d,ownerStoreExpenses:d.ownerStoreExpenses.filter(e=>e.id!==id)}))}/>}
    {page==='Payslips'&&<Payslips employees={active} month={selectedMonth} setMonth={setSelectedMonth} payrollFor={payrollFor} setModal={setModal}/>} 
   </div>
  </main>
  <nav className="mobile-nav">{nav.map(n=>{const I=navIcons[n];return <button key={n} className={page===n?'active':''} onClick={()=>{setPage(n);window.scrollTo({top:0,behavior:'smooth'})}}><I/><span>{n==='Store Expenses'?'Store':n}</span></button>})}</nav>
  {modal==='employee'&&<EmployeeModal close={()=>setModal(null)} save={saveEmployee}/>} 
  {modal==='expense'&&<ExpenseModal close={()=>setModal(null)} save={saveExpense} employees={active}/>} 
  {modal?.type==='storeExpense'&&<StoreExpenseModal close={()=>setModal(null)} save={saveStoreExpense} employees={active} initialPayer={modal.payer}/>}
  {modal==='settings'&&<SettingsModal close={()=>setModal(null)} save={connectSheet} tokenValue={sheetToken}/>} 
  {modal?.type==='payslip'&&<PayslipModal close={()=>setModal(null)} employee={modal.employee} month={selectedMonth} pay={payrollFor(modal.employee)} expenses={monthExp.filter(e=>e.employeeId===modal.employee.id)}/>} 
 </div>
}

function Dashboard({data,active,payrollFor,expenses,setPage,setModal,selectedMonth}){const present=data.attendance.filter(a=>a.date===today&&a.status==='Present').length;const marked=data.attendance.filter(a=>a.date===today).length;const payroll=active.reduce((s,e)=>s+payrollFor(e).net,0);const deduction=expenses.reduce((s,e)=>s+Number(e.amount),0);return <>
 <section className="hero"><div><span className="eyebrow">{new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</span><h2>Good afternoon! <span>Here’s today’s overview.</span></h2></div><button className="whitebtn" onClick={()=>setPage('Attendance')}><CalendarCheck2 size={18}/>Mark attendance<ArrowUpRight size={17}/></button></section>
 <div className="stats">
  <Stat icon={Users} tone="violet" label="Total employees" value={active.length} note={`${active.length} active employees`}/>
  <Stat icon={CalendarCheck2} tone="green" label="Present today" value={`${present}/${active.length}`} note={marked<active.length?`${active.length-marked} attendance pending`:`${active.length-present} absent today`}/>
  <Stat icon={BadgeIndianRupee} tone="blue" label="Estimated payroll" value={money(payroll)} note={new Date(selectedMonth+'-01').toLocaleDateString('en-IN',{month:'long',year:'numeric'})}/>
  <Stat icon={WalletCards} tone="orange" label="Monthly deductions" value={money(deduction)} note={`${expenses.length} expense entries`}/>
 </div>
 <div className="grid-main">
  <section className="panel"><PanelHead title="Today’s attendance" sub={`${marked} of ${active.length} employees marked`} action="View all" onClick={()=>setPage('Attendance')}/><div className="attendance-list">{active.slice(0,5).map((e,i)=>{const a=data.attendance.find(a=>a.employeeId===e.id&&a.date===today);return <div className="employee-row" key={e.id}><Avatar name={e.name} i={i}/><div className="grow"><b>{e.name}</b><span>{e.designation}</span></div><Status status={a?.status||'Not marked'}/></div>})}</div></section>
  <section className="panel"><PanelHead title="Recent expenses" sub="Latest employee deductions" action="View all" onClick={()=>setPage('Expenses')}/><div className="expense-list">{data.expenses.slice(0,4).map((x,i)=>{const e=data.employees.find(e=>e.id===x.employeeId);return <div className="expense-row" key={x.id}><div className={`expense-icon ${x.category.toLowerCase()}`}>{x.category==='Advance'?<HandCoins/>:x.category==='Product'?<Package/>:x.category==='Travel'?<Bus/>:<UtensilsCrossed/>}</div><div className="grow"><b>{x.description}</b><span>{e?.name} · {fmtDate(x.date)}</span></div><strong>-{money(x.amount)}</strong></div>})}</div></section>
 </div>
 <section className="panel payroll-preview"><PanelHead title="This month’s payroll" sub="Calculated from attendance and deductions" action="View payslips" onClick={()=>setPage('Payslips')}/><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Days worked</th><th>Monthly salary</th><th>Deductions</th><th>Net payable</th><th></th></tr></thead><tbody>{active.map((e,i)=>{const p=payrollFor(e);return <tr key={e.id}><td><div className="person"><Avatar name={e.name} i={i}/><div><b>{e.name}</b><span>{e.id}</span></div></div></td><td><b>{p.worked}</b> <span className="muted">/ {p.days}</span></td><td>{money(e.salary)}</td><td className="negative">-{money(p.deduct)}</td><td><strong>{money(p.net)}</strong></td><td><button className="plain" onClick={()=>setModal({type:'payslip',employee:e})}>View slip</button></td></tr>})}</tbody></table></div></section>
 </>}
function Stat({icon:Icon,tone,label,value,note}){return <div className="stat"><div className={`stat-icon ${tone}`}><Icon/></div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>}
function PanelHead({title,sub,action,onClick}){return <div className="panel-head"><div><h3>{title}</h3><p>{sub}</p></div><button onClick={onClick}>{action}<ArrowUpRight size={15}/></button></div>}
function Avatar({name,i=0}){return <div className={`avatar ${colors[i%colors.length]}`}>{initials(name)}</div>}
function Status({status}){return <span className={`status ${status.toLowerCase().replace(' ','-')}`}>{status==='Present'?<Check/>:status==='Absent'?<X/>:<Clock3/>}{status}</span>}

function Employees({employees,query,setQuery,setModal}){const list=employees.filter(e=>(e.name+e.phone+e.email+e.id+e.designation).toLowerCase().includes(query.toLowerCase()));return <section className="panel full"><Toolbar query={query} setQuery={setQuery} placeholder="Search name, email, phone or employee ID"/><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Phone</th><th>Email</th><th>PAN card</th><th>Designation</th><th>Monthly salary</th><th>Status</th><th></th></tr></thead><tbody>{list.map((e,i)=><tr key={e.id}><td><div className="person"><Avatar name={e.name} i={i}/><div><b>{e.name}</b><span>{e.id} · Joined {fmtDate(e.joined)}</span></div></div></td><td>{e.phone}</td><td>{e.email||<span className="muted">Not added</span>}</td><td className="mono">{e.pan}</td><td>{e.designation}</td><td><strong>{money(e.salary)}</strong></td><td><span className="dot-active">{e.status}</span></td><td><button className="iconbtn"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table></div></section>}
function Toolbar({query,setQuery,placeholder}){return <div className="toolbar"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder}/></div><button className="filter">All employees<ChevronDown size={16}/></button></div>}

function Attendance({employees,attendance,date,setDate,setAttendance}){const marked=attendance.filter(a=>a.date===date);const p=marked.filter(a=>a.status==='Present').length,a=marked.filter(a=>a.status==='Absent').length;return <><div className="attendance-top"><div className="date-control"><CalendarCheck2/><div><span>Attendance date</span><input type="date" value={date} max={today} onChange={e=>setDate(e.target.value)}/></div></div><div className="attendance-summary"><div><b>{p}</b><span>Present</span></div><div><b>{a}</b><span>Absent</span></div><div><b>{employees.length-p-a}</b><span>Not marked</span></div></div></div><section className="panel full"><div className="panel-head"><div><h3>Employee attendance</h3><p>Select present or absent for each employee</p></div><span className="progress-text">{marked.length} of {employees.length} completed</span></div><div className="mark-list">{employees.map((e,i)=>{const s=marked.find(x=>x.employeeId===e.id)?.status;return <div className="mark-row" key={e.id}><Avatar name={e.name} i={i}/><div className="grow"><b>{e.name}</b><span>{e.designation} · {e.id}</span></div><div className="mark-actions"><button className={s==='Present'?'present selected':'present'} onClick={()=>setAttendance(e.id,'Present')}><Check/>Present</button><button className={s==='Absent'?'absent selected':'absent'} onClick={()=>setAttendance(e.id,'Absent')}><X/>Absent</button></div></div>})}</div></section></>}

function Expenses({expenses,employees,query,setQuery,setModal,remove}){const list=expenses.filter(x=>{const e=employees.find(e=>e.id===x.employeeId);return (x.description+x.category+e?.name).toLowerCase().includes(query.toLowerCase())});return <><div className="expense-summary"><div><span>Total expenses this month</span><strong>{money(expenses.filter(e=>e.date.startsWith(monthKey)).reduce((s,e)=>s+e.amount,0))}</strong><small>Will be deducted from employee salaries</small></div><WalletCards/></div><section className="panel full"><Toolbar query={query} setQuery={setQuery} placeholder="Search expenses or employee"/><div className="table-wrap"><table><thead><tr><th>Date</th><th>Employee</th><th>Type</th><th>Description</th><th>Amount</th><th></th></tr></thead><tbody>{list.map((x,i)=>{const e=employees.find(e=>e.id===x.employeeId);return <tr key={x.id}><td>{fmtDate(x.date)}</td><td><div className="person compact"><Avatar name={e?.name||'?'} i={i}/><div><b>{e?.name}</b><span>{e?.id}</span></div></div></td><td><span className={`category ${x.category.toLowerCase()}`}>{x.category}</span></td><td>{x.description}</td><td className="negative"><strong>-{money(x.amount)}</strong></td><td><button className="iconbtn danger" onClick={()=>remove(x.id)}><Trash2 size={16}/></button></td></tr>})}</tbody></table></div></section></>}

function StoreExpenses({employeeExpenses,ownerExpenses,employees,setModal,removeEmployee,removeOwner}){const [view,setView]=useState('employee'),[search,setSearch]=useState('');const source=view==='employee'?employeeExpenses:ownerExpenses;const total=items=>items.filter(x=>x.date.startsWith(monthKey)).reduce((sum,x)=>sum+Number(x.amount),0);const list=source.filter(x=>{const employee=employees.find(e=>e.id===x.employeeId);return `${x.description} ${x.category} ${employee?.name||''}`.toLowerCase().includes(search.toLowerCase())});return <>
 <div className="store-summary-grid"><div className="store-summary employee"><div><span>Employee store expenses</span><strong>{money(total(employeeExpenses))}</strong><small>Business costs handled through employees</small></div><Fuel/></div><div className="store-summary owner"><div><span>Owner store expenses</span><strong>{money(total(ownerExpenses))}</strong><small>Business costs paid directly by owner</small></div><Store/></div></div>
 <section className="panel full"><div className="store-toolbar"><div className="store-tabs"><button className={view==='employee'?'active':''} onClick={()=>setView('employee')}>Employee-paid</button><button className={view==='owner'?'active':''} onClick={()=>setView('owner')}>Owner-paid</button></div><div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search store expenses"/></div><button className="primary" onClick={()=>setModal({type:'storeExpense',payer:view})}><Plus size={17}/>Add {view==='employee'?'employee':'owner'} expense</button></div><div className="payroll-note"><ShieldCheck size={17}/><span>These are business expenses only. They are not deducted from salary and never appear on employee payslips.</span></div><div className="table-wrap"><table><thead><tr><th>Date</th>{view==='employee'&&<th>Employee</th>}<th>Type</th><th>Description</th><th>Amount</th><th></th></tr></thead><tbody>{list.length?list.map((x,i)=>{const employee=employees.find(e=>e.id===x.employeeId);return <tr key={x.id}><td>{fmtDate(x.date)}</td>{view==='employee'&&<td><div className="person compact"><Avatar name={employee?.name||'?'} i={i}/><div><b>{employee?.name||'Unknown employee'}</b><span>{employee?.id}</span></div></div></td>}<td><span className={`category ${x.category.toLowerCase().replaceAll(' ','-')}`}>{x.category}</span></td><td>{x.description}</td><td><strong>{money(x.amount)}</strong></td><td><button className="iconbtn danger" onClick={()=>view==='employee'?removeEmployee(x.id):removeOwner(x.id)}><Trash2 size={16}/></button></td></tr>}):<tr><td colSpan={view==='employee'?6:5} className="empty-state">No {view}-paid store expenses added yet.</td></tr>}</tbody></table></div></section>
 </>}

function Payslips({employees,month,setMonth,payrollFor,setModal}){return <><div className="month-bar"><div><span>Salary month</span><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div><p>Salary is calculated using {daysInMonth(month)} calendar days in this month.</p></div><div className="payslip-grid">{employees.map((e,i)=>{const p=payrollFor(e);return <div className="pay-card" key={e.id}><div className="pay-person"><Avatar name={e.name} i={i}/><div><b>{e.name}</b><span>{e.designation} · {e.id}</span></div><button><MoreHorizontal/></button></div><div className="pay-math"><div><span>Days worked</span><b>{p.worked} / {p.days}</b></div><div><span>Earned salary</span><b>{money(p.gross)}</b></div><div><span>Deductions</span><b className="negative">-{money(p.deduct)}</b></div></div><div className="net"><span>Net payable</span><strong>{money(p.net)}</strong></div><button className="slipbtn" onClick={()=>setModal({type:'payslip',employee:e})}><FileText/>View & print payslip</button></div>})}</div></>}

function Modal({children,close,wide=false}){return <div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className={wide?'modal wide':'modal'}>{children}</div></div>}
function EmployeeModal({close,save}){const [f,setF]=useState({name:'',phone:'',email:'',pan:'',designation:'',salary:'',joined:today});const field=(k,v)=>setF(x=>({...x,[k]:v}));return <Modal close={close}><ModalHead icon={UserPlus} title="Add new employee" sub="Employee number will be assigned automatically" close={close}/><form onSubmit={e=>{e.preventDefault();save(f)}}><div className="form-grid"><Label text="Full name"><input required value={f.name} onChange={e=>field('name',e.target.value)} placeholder="Employee full name"/></Label><Label text="Phone number"><input required value={f.phone} onChange={e=>field('phone',e.target.value)} placeholder="10-digit number"/></Label><Label text="Email address"><input required type="email" value={f.email} onChange={e=>field('email',e.target.value.trim())} placeholder="employee@example.com"/></Label><Label text="PAN card number"><input required value={f.pan} onChange={e=>field('pan',e.target.value.toUpperCase())} placeholder="ABCDE1234F" pattern="[A-Z]{5}[0-9]{4}[A-Z]"/></Label><Label text="Designation"><input required value={f.designation} onChange={e=>field('designation',e.target.value)} placeholder="e.g. Sales Executive"/></Label><Label text="Monthly salary"><div className="input-icon">₹<input required type="number" min="0" value={f.salary} onChange={e=>field('salary',e.target.value)} placeholder="0"/></div></Label><Label text="Joining date"><input required type="date" value={f.joined} onChange={e=>field('joined',e.target.value)}/></Label></div><FormActions close={close} text="Add employee"/></form></Modal>}
function ExpenseModal({close,save,employees}){const [f,setF]=useState({employeeId:employees[0]?.id||'',date:today,category:'Advance',amount:'',description:''});const field=(k,v)=>setF(x=>({...x,[k]:v}));return <Modal close={close}><ModalHead icon={WalletCards} title="Add employee expense" sub="This amount will be deducted from salary" close={close}/><form onSubmit={e=>{e.preventDefault();save(f)}}><Label text="Employee"><select value={f.employeeId} onChange={e=>field('employeeId',e.target.value)}>{employees.map(e=><option key={e.id} value={e.id}>{e.name} — {e.id}</option>)}</select></Label><div className="form-grid"><Label text="Date"><input type="date" value={f.date} onChange={e=>field('date',e.target.value)}/></Label><Label text="Expense type"><select value={f.category} onChange={e=>field('category',e.target.value)}><option>Advance</option><option>Product</option><option>Travel</option><option>Other</option></select></Label></div><Label text="Amount"><div className="input-icon">₹<input required type="number" min="1" value={f.amount} onChange={e=>field('amount',e.target.value)} placeholder="0"/></div></Label><Label text="Description"><textarea required value={f.description} onChange={e=>field('description',e.target.value)} placeholder="What was this expense for?"/></Label><FormActions close={close} text="Add expense"/></form></Modal>}
function StoreExpenseModal({close,save,employees,initialPayer}){const [f,setF]=useState({payer:initialPayer||'employee',employeeId:employees[0]?.id||'',date:today,category:'Petrol',amount:'',description:''});const field=(k,v)=>setF(x=>({...x,[k]:v}));return <Modal close={close}><ModalHead icon={Store} title="Add store expense" sub="Recorded separately and excluded from employee payroll" close={close}/><form onSubmit={e=>{e.preventDefault();save(f)}}><Label text="Paid or handled by"><select value={f.payer} onChange={e=>field('payer',e.target.value)}><option value="employee">Employee</option><option value="owner">Owner</option></select></Label>{f.payer==='employee'&&<Label text="Employee"><select required value={f.employeeId} onChange={e=>field('employeeId',e.target.value)}>{employees.map(e=><option key={e.id} value={e.id}>{e.name} — {e.id}</option>)}</select></Label>}<div className="form-grid"><Label text="Date"><input required type="date" value={f.date} onChange={e=>field('date',e.target.value)}/></Label><Label text="Expense type"><select value={f.category} onChange={e=>field('category',e.target.value)}><option>Petrol</option><option>Delivery</option><option>Purchase</option><option>Maintenance</option><option>Food</option><option>Other</option></select></Label></div><Label text="Amount"><div className="input-icon">₹<input required type="number" min="1" value={f.amount} onChange={e=>field('amount',e.target.value)} placeholder="0"/></div></Label><Label text="Description"><textarea required value={f.description} onChange={e=>field('description',e.target.value)} placeholder="What was this store expense for?"/></Label><div className="info-box"><ShieldCheck/><div><b>Not a salary deduction</b><span>This expense will not be shown on any employee payslip.</span></div></div><FormActions close={close} text="Add store expense"/></form></Modal>}
function SettingsModal({close,save,tokenValue}){const [token,setToken]=useState(tokenValue);return <Modal close={close}><ModalHead icon={Database} title="Secure Sheet access" sub="Connect this browser to your payroll records" close={close}/><div className="info-box"><ShieldCheck/><div><b>The Google Sheets backend is already configured</b><span>Enter your private access code once. It stays saved only on this device.</span></div></div><Label text="Private access code"><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Enter your private access code"/></Label><div className="setup-steps"><b>Using another phone or computer?</b><span>Enter the same private code once on that device. Normal refreshes and future visits will remain connected automatically.</span></div><div className="form-actions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>save({token})} disabled={!token}><Cloud/>Connect securely</button></div></Modal>}
function ModalHead({icon:Icon,title,sub,close}){return <div className="modal-head"><div className="modal-icon"><Icon/></div><div><h2>{title}</h2><p>{sub}</p></div><button onClick={close}><X/></button></div>}
function Label({text,children}){return <label><span>{text}</span>{children}</label>}
function FormActions({close,text}){return <div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" type="submit"><Save/>{text}</button></div>}

function PayslipModal({close,employee,month,pay,expenses}){const monthName=new Date(month+'-01').toLocaleDateString('en-IN',{month:'long',year:'numeric'});return <Modal close={close} wide><div className="payslip-actions no-print"><button className="secondary" onClick={close}><ChevronLeft/>Back</button><button className="primary" onClick={()=>window.print()}><Printer/>Print payslip</button></div><article className="payslip"><div className="slip-brand"><img src={LOGO} alt="Bhansali Medisales"/><span>Employee salary statement</span></div><div className="slip-business"><div><MapPin/><span>{BUSINESS.address}</span></div><div><b>GSTIN</b><span>{BUSINESS.gstin}</span></div><div><b>Drug Licence</b><span>{BUSINESS.drug}</span></div><div><b>FSSAI</b><span>{BUSINESS.fssai}</span></div></div><div className="slip-title"><span>Payslip for</span><h1>{monthName}</h1></div><div className="slip-employee"><div><span>Employee name</span><b>{employee.name}</b></div><div><span>Employee number</span><b>{employee.id}</b></div><div><span>Designation</span><b>{employee.designation}</b></div><div><span>PAN number</span><b>{employee.pan}</b></div><div><span>Phone number</span><b>{employee.phone}</b></div><div><span>Email address</span><b>{employee.email||'Not provided'}</b></div></div><table className="slip-table"><thead><tr><th>Earnings</th><th>Calculation</th><th>Amount</th></tr></thead><tbody><tr><td>Monthly salary</td><td>{money(employee.salary)} ÷ {pay.days} days</td><td>{money(employee.salary)}</td></tr><tr><td>Salary earned</td><td>{pay.worked} days × {money(pay.daily)}</td><td>{money(pay.gross)}</td></tr></tbody></table><table className="slip-table deductions"><thead><tr><th>Deductions</th><th>Description</th><th>Amount</th></tr></thead><tbody>{expenses.length?expenses.map(x=><tr key={x.id}><td>{x.category}<small>{fmtDate(x.date)}</small></td><td>{x.description}</td><td>{money(x.amount)}</td></tr>):<tr><td colSpan="2">No deductions this month</td><td>{money(0)}</td></tr>}<tr className="total"><td colSpan="2">Total deductions</td><td>{money(pay.deduct)}</td></tr></tbody></table><div className="slip-net"><div><span>Net salary payable</span><small>Earned salary minus deductions</small></div><strong>{money(pay.net)}</strong></div><div className="slip-foot"><span>This is a computer-generated payslip.</span><b>Authorised Signatory</b></div></article></Modal>}

createRoot(document.getElementById('root')).render(<App/>);
